// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCOSNbUBFigijQOspIpmsW8yczKKmWWV4',
    appId: '1:1020840793702:web:de2a2148608d9e912effa7',
    messagingSenderId: '1020840793702',
    projectId: 'mobilesemester4',
    authDomain: 'mobilesemester4.firebaseapp.com',
    storageBucket: 'mobilesemester4.firebasestorage.app',
    measurementId: 'G-KD0RJV5RKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-sduJkQG5vYm11OVI0ydaCHzTkBSHCYM',
    appId: '1:1020840793702:android:de54bc28f19bdf8e2effa7',
    messagingSenderId: '1020840793702',
    projectId: 'mobilesemester4',
    storageBucket: 'mobilesemester4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOqc4rkXylQ3Jl8ZevPpXeNKXrzdtH3Y',
    appId: '1:1020840793702:ios:418d952f9f88bfca2effa7',
    messagingSenderId: '1020840793702',
    projectId: 'mobilesemester4',
    storageBucket: 'mobilesemester4.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmOqc4rkXylQ3Jl8ZevPpXeNKXrzdtH3Y',
    appId: '1:1020840793702:ios:418d952f9f88bfca2effa7',
    messagingSenderId: '1020840793702',
    projectId: 'mobilesemester4',
    storageBucket: 'mobilesemester4.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCOSNbUBFigijQOspIpmsW8yczKKmWWV4',
    appId: '1:1020840793702:web:7f3221c8246b57de2effa7',
    messagingSenderId: '1020840793702',
    projectId: 'mobilesemester4',
    authDomain: 'mobilesemester4.firebaseapp.com',
    storageBucket: 'mobilesemester4.firebasestorage.app',
    measurementId: 'G-YYKGJFY915',
  );
}
